### ISSUE TITLE
cmake error on osx

### ISSUE THREAD

**Issue by agoetz** [Amber-MD/CMakeConfigScripts#2] opened 2017-07-28 09:01 UTC
@multiplemonomials cmake fails on my macbook. I haven't had time to look into it but am attaching console output and log files. If you see something obvious let me know. Thanks.

[console-log.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1182530/console-log.txt)
[CMakeCache.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1182531/CMakeCache.txt)
[CMakeOutput.log.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1182533/CMakeOutput.log.txt)

**Comment by multiplemonomials** [comment] 2017-07-28 14:41
Can you try again?  It should be fixed in the commit I just pushed.

**Comment by hainm** [comment] 2017-08-02 04:10
Jamie

I got below error with my macOS 10.12.6. 
```
Warning: Unused variable ‘t5’ declared at (1) [-Wunused-variable]
yes
checking for strings.h... [  2%] Building Fortran object AmberTools/src/arpack/CMakeFiles/arpack.dir/dstqrb.f.o
yes
checking for inttypes.h... [  2%] Building C object AmberTools/src/arpack/CMakeFiles/arpack.dir/wallclock.c.o
yes
checking for stdint.h... [  3%] Linking Fortran shared library libarpack.dylib
Undefined symbols for architecture x86_64:
  "__gfortran_st_write", referenced from:
      _ivout_ in ivout.f.o
      _dvout_ in dvout.f.o
      _dnaupd_ in dnaupd.f.o
      _dmout_ in dmout.f.o
      _dsaupd_ in dsaupd.f.o
  "__gfortran_st_write_done", referenced from:
      _ivout_ in ivout.f.o
      _dvout_ in dvout.f.o
      _dnaupd_ in dnaupd.f.o
      _dmout_ in dmout.f.o
      _dsaupd_ in dsaupd.f.o
  "__gfortran_transfer_array_write", referenced from:
      _dmout_ in dmout.f.o
  "__gfortran_transfer_character_write", referenced from:
      _ivout_ in ivout.f.o
      _dvout_ in dvout.f.o
      _dmout_ in dmout.f.o
  "__gfortran_transfer_integer_write", referenced from:
      _ivout_ in ivout.f.o
      _dvout_ in dvout.f.o
      _dnaupd_ in dnaupd.f.o
      _dmout_ in dmout.f.o
      _dsaupd_ in dsaupd.f.o
  "__gfortran_transfer_real_write", referenced from:
      _dvout_ in dvout.f.o
      _dnaupd_ in dnaupd.f.o
      _dmout_ in dmout.f.o
      _dsaupd_ in dsaupd.f.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
yes
make[2]: *** [AmberTools/src/arpack/libarpack.dylib] Error 1
make[1]: *** [AmberTools/src/arpack/CMakeFiles/arpack.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
checking for unistd.h... yes
checking fpu_control.h usability... no
checking fpu_control.h presence... no
checking for fpu_control.h... no
checking whether x86 FPU control code is needed... yes
checking for m4... m4
checking whether we are using GNU m4... yes
checking for indent... indent
indent: Command line: ``-cs'' requires a parameter
configure: creating ./config.status
config.status: creating make.inc
config.status: executing gen_makefile commands
[  3%] Performing build step for 'xblas'
[  3%] No install step for 'xblas'
[  3%] Completed 'xblas'
[  3%] Built target xblas
make: *** [all] Error 2
```

What I did

```
cmake ../amber -DCMAKE_INSTALL_PREFIX=`pwd`
make -j 2
```

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin15/6.1.0/lto-wrapper
Target: x86_64-apple-darwin15
Configured with: ../gcc-6.1.0/configure --prefix=/usr/local/gfortran --with-gmp=/Users/fx/devel/gcc/deps-static/x86_64 --enable-languages=c,c++,fortran,objc,obj-c++ --build=x86_64-apple-darwin15
Thread model: posix
gcc version 6.1.0 (GCC) 
```

```
$ clang -v
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

git
```
commit f7d1af552de0e3b1da96dcc9a7312a3bd6fde53b
Author: Jamie Smith <jsmith@crackofdawn.onmicrosoft.com>
Date:   Tue Aug 1 20:33:19 2017 -0700

    Update cphstats to fix CMake build
```

**Comment by multiplemonomials** [comment] 2017-08-02 08:28
What CMake version are you using?  Have you tried the latest version?  I have seen somewhat similar errors that were caused by bugs in CMake 3.4.

Are those symbols present in libgfortran?  

Can you send me the output of running `make -j1 VERBOSE=1`

**Comment by hainm** [comment] 2017-08-02 13:42
V3.7 and not tried recent version yet.

I will post output tonight. 

Not sure about gfortran symbols but i have been using it with non-cmake

**Comment by hainm** [comment] 2017-08-03 00:06
Upgrade to latest cmake (v3.9) does help. thanks.

**Comment by hainm** [comment] 2017-08-03 01:35
uhm, actually another error.
[log.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1195736/log.txt)

**Comment by multiplemonomials** [comment] 2017-08-03 02:12
Looks like `AppleClang` is bugging out when trying to compile a MTK++ source file.  Can you try disabling clang (`-DFORCE_DISABLE_TOOLS`), or building with gcc (delete all files in build directory, then rerun with `-DCOMPILER=gnu`)?

**Comment by hainm** [comment] 2017-08-03 03:25
> or building with gcc (delete all files in build directory, then rerun with -DCOMPILER=gnu)

```
cmake DFORCE_DISABLE_TOOLS=mtkpp -DCMAKE_INSTALL_PREFIX=`pwd` ../amber -DCOMPILER=gnu
make -j 1
```

```
...
/Users/haichit/amber_git/amber/AmberTools/src/mtkpp/src/eigen3b2/Eigen/src/Eigenvalues/./ComplexSchur.h:359:66: warning: unused typedef
      'ComplexMatrixType' [-Wunused-local-typedef]
    typedef typename ComplexSchur<MatrixType>::ComplexMatrixType ComplexMatrixType;
                                                                 ^
fatal error: error in backend: Unsupported expression in static initializer: extractelement (<4 x i32> bitcast
      (<2 x i64> <i64 0, i64 undef> to <4 x i32>), i32 0)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/pca-4a8e72.cpp
clang: note: diagnostic msg: /var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/pca-4a8e72.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/haichit/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make[2]: *** [AmberTools/src/mtkpp/src/Statistics/CMakeFiles/mtkpp_statistics.dir/pca.cpp.o] Error 70
make[1]: *** [AmberTools/src/mtkpp/src/Statistics/CMakeFiles/mtkpp_statistics.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by multiplemonomials** [comment] 2017-08-03 03:33
Hmm it looks like neither of the options you passed to CMake are having any effect.  First of all, I think `../amber` needs to be the last argument to CMake.  Also, you're missing a hyphen in front of `DFORCE_DISABLE_TOOLS=mtkpp`.

To effectively diagnose issues like this I need a bit more information.  I have created a [page on the wiki](http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Reporting-A-Bug) that details exactly what to submit.

**Comment by hainm** [comment] 2017-08-03 04:07
thanks.

> cmake -DFORCE_DISABLE_TOOLS=mtkpp -DCMAKE_INSTALL_PREFIX=`pwd` -DCOMPILER=gnu ../amber

I was able to "make install" with above command. Getting some issues with pytraj 
```bash
$ python -c "import pytraj; print(pytraj)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
  File "pytraj/math/cpp_math.pxd", line 28, in init pytraj.core.topology_objects
  File "/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/math/__init__.py", line 3, in <module>
    from .cpp_math import Vec3, Matrix_3x3, Grid, torsion, angle, distance_ as distance
  File "pytraj/topology/topology.pxd", line 147, in init pytraj.math.cpp_math
ImportError: dlopen(/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so, 2): Symbol not found: __ZN8FileName11SetFileNameERKSs
  Referenced from: /Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so
  Expected in: /Users/haichit/amber_git/build/lib/libcpptraj.dylib
 in /Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so
```

This is a known problem with if linking libcpptraj to `/usr/lib/libstdc++.6.dylib`
```
$ otool -L /Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so 
/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so:
	/Users/haichit/amber_git/amber/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

PS: I think we have a fix for that with non-cmake by adding "-stdlib=libstdc++" to cpptraj flags (check configure2).

**Comment by hainm** [comment] 2017-08-03 04:10
```
$ otool -L /Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so 
/Users/haichit/amber_git/build/lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so:
	/Users/haichit/amber_git/amber/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
```

Actually this is weird.
```
$ ls /Users/haichit/amber_git/amber/lib/libcpptraj.dylib
ls: /Users/haichit/amber_git/amber/lib/libcpptraj.dylib: No such file or directory
```

Should be 
"/Users/haichit/amber_git/build/lib/libcpptraj.dylib"

I guess this is due to pytraj is using `rpath` at install time?

**Comment by hainm** [comment] 2017-08-03 04:10
> I guess this is due to pytraj is using rpath at install time?

With the binary distribution for At17, we update this via conda build that takes care of all those stuff.

**Comment by multiplemonomials** [comment] 2017-08-03 04:18
...so what exactly is the problem?  I am a bit confused.  Is it that the RPATH of the pytraj extension modules is wrong?  `amber.sh` sets `DYLD_LIBRARY_PATH`, which should take precedence over the RPATH, right?

**Comment by hainm** [comment] 2017-08-03 04:28
> ...so what exactly is the problem? I am a bit confused.

uhm there are two issues above but just need to handle this first

> Symbol not found: __ZN8FileName11SetFileNameERKSs

Sorry for the confusion.

My guess is that "pytraj" was linked to "/usr/lib/libstdc++.6.dylib" (Miniconda Python forces that) while "libcpptraj.dylib" was linked to "/usr/lib/libc++.dylib". That's why while compiling "libcpptraj", we are using ""-stdlib=libstdc++" to handle the case.

**Comment by hainm** [comment] 2017-08-03 04:29
libcpptraj: /usr/lib/libc++.1.dylib 
```
$ otool -L lib/libcpptraj.dylib | grep libc
lib/libcpptraj.dylib:
	@rpath/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

pytraj: usr/lib/libstdc++.6.dylib 
```
$ otool -L ./lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so 
./lib/python3.5/site-packages/pytraj/topology/topology.cpython-35m-darwin.so:
	/Users/haichit/amber_git/amber/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

**Comment by multiplemonomials** [comment] 2017-08-03 04:31
Oh, I see.  Try adding
```cmake
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "AppleClang")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libstdc++")
endif()
```
at line 52 of `AmberTools/src/cpptraj/CMakeLists.txt`, and rebuild and see if that fixes it.

**Comment by hainm** [comment] 2017-08-03 04:31
I think it will. Will try tmr. G9 Jamie.

**Comment by multiplemonomials** [comment] 2017-08-03 04:34
Also, have you checked out the CMake option `-DUSE_MINICONDA=TRUE`?

**Comment by agoetz** [comment] 2017-08-03 06:14
I tried the build on OSX 10.11.6 (El Capitan):
* configures and builds with clang if I disable mtkpp (`-DFORCE_DISABLE_TOOLS=mtkpp`)
* configures and builds with gnu compilers 5.4.0 installed through macports
* install of python with `-DUSE_MINICONDA=TRUE works` (pytraj still does not work, should it?)

I ran the serial tests for the gnu build. I had to set `export BINDIR=$AMBERHOME/bin` to get the Amber (pmemd) tests to run. Is this new?

150 tests pass, 1 fails (test/nfe/smd2). Looks pretty good.

AmberTools:
1196 file comparisons passed,  24 file comparisons failed, 378 tests experienced errors

Will look at it later. Too tired now and busy with SDSC Summer Institute.

**Comment by multiplemonomials** [comment] 2017-08-05 00:05
Gah, my OS X VM is now refusing to boot, and I have no idea how to fix it.  Do any of you have anything like a spare OS X PC or laptop at one of your offices that I could TeamViewer (preferably) or SSH into to test my code on?  Otherwise I might be unable to test the CMake build system on OS X myself since I have no access to any macs.

Also, is there any problem with having all Amber programs link to libstdc++ on AppleClang?  It feels a bit kludgy to use different c++ libraries for different programs.

**Closed** 2017-08-05 01:12 UTC

**Comment by multiplemonomials** [comment] 2017-08-05 04:58
@agoetz Are you able to help me with the above problem?

**Comment by agoetz** [comment] 2017-08-05 05:32
@multiplemonomials I have a spare macbook that I can hook up to my network at SDSC so you can log in through gecko. But its charger is broken, I have to get one from home first. May not happen before Monday.

**Comment by multiplemonomials** [comment] 2017-08-05 05:44
Thanks a ton.  Does it have the Intel compilers and MKL installed?  I'd like to test those, but I'll need you to install them if I will only have command-line access.

**Comment by hainm** [comment] 2017-08-05 05:46
per mkl, you can use conda from Miniconda

```python
conda install mkl
```

**Comment by multiplemonomials** [comment] 2017-08-13 05:37
I have submitted the Clang bug to Apple, as bug #33866126
